export default {
    GAME_WIDTH: 800,
    GAME_HEIGHT: 600,
    HEADER_HEIGHT: 70,
    SIDE_PANEL_WIDTH: 180,
    MENU_BACKGROUND_COLOR: 0xb0b0b0,
    MENU_BACKGROUND_ALPHA: 0.5,
    MONEY_FONT_COLOR: "#FFCC00",

};