export default {
    GAME_WIDTH: 800,
    GAME_HEIGHT: 600,
    HEADER_HEIGHT: 70,
    SIDE_PANEL_WIDTH: 180,
    MENU_BACKGROUND_COLOR: 0xb0b0b0,
    MENU_BACKGROUND_ALPHA: 0.5,
    MONEY_FONT_COLOR: "#FFCC00",
    BUY_TEXT_COLOR: "#c4a747",
    BUY_STROKE_COLOR: "#e0c56e",
    BUY_HOVER_COLOR: "#ff0",
    TEXT_SHADOW_COLOR: "#333333",
    DISABLED_COLOR: "#ABABAB",
    MANAGER_SPRITE: 'assets/sprites/manager.png'

};